{% set name = "buildkite-test-collector" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8a1a1873dd2108995ba2242317b6e8d48b91dd0618c22da9b6eae0d2751f2627

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2
    - pytest >=7

test:
  imports:
    - buildkite_test_collector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/buildkite/test-collector-python
  summary: Buildkite Test Analytics collector
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bstadlbauer
