{% set name = "buildkite-test-collector" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 541d3dcbe8f6c69121ce2a12d61fbae0ae38243b666b380c8d48670a194e1ec5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2
    - pytest >=7

test:
  imports:
    - buildkite_test_collector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/buildkite/test-collector-python
  summary: Buildkite Test Analytics collector
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bstadlbauer
